### PR TITLE
DEV_website attempt

### PR DESCRIPTION
**Pull request by giorgiacek**
Not sure it make sense to PR, nothing has changed, I just added DEV_website to the YAML so that my commits should have triggered the pkgdown workflow directly (they do, but the workflow which adds to gh-pages fails). But after the PR we should then add DEV to the YAML.

### CODE REVIEW

**Comment by randrescastaneda** [comment]
Task linked: [CU-868703b5w build website](https://app.clickup.com/t/868703b5w)

**Comment by randrescastaneda** [comment]
hi @giorgiacek , 

I think it makes sense to merge into DEV once the examples of all functions are ready and, ideally, the vignettes as well. We don't really need to merge into `DEV` to make it work. In fact, you can merge into this branch all the advancements of the other branches (e.g., `md_functions_examples` and the like) once they have been fully approved. Please let me know if it is clear.

**Comment by giorgiacek** [comment]
hi @randrescastaneda, yes it makes sense. I think I am done now with gd_functions and md_functions. And I am drafting the vignettes. So I switched to DEV_website. I assume: you (or should I?) will merge both (gd_examples and md_examples) into DEV_website, I start working on DEV_website, I push to deployment through DEV_website.

**Comment by randrescastaneda** [comment]
> hi @randrescastaneda, yes it makes sense. I think I am done now with gd_functions and md_functions. And I am drafting the vignettes. So I switched to DEV_website. I assume: you (or should I?) will merge both (gd_examples and md_examples) into DEV_website, I start working on DEV_website, I push to deployment through DEV_website.

Hi @giorgiacek, Thanks. 
You can now merge the most recent versions of `md_functions` and `gd_functions` into `DEV_website`, they already include your examples. Just be aware that you may find conflicts you need to resolve and that some of the tests are not passing right now. Rossana is working on them right now. Yet, I think they work fine enough for you to start writing the vignettes Next week, Zander will finish the S3 methods, so that you can write another vignette about them (which is the most important). Also, make use of the current information in the readme.md file. I think it is too long and much of what is in there could go in vignettes. Please, let me know if you have questions.

**Review by randrescastaneda — APPROVED** [review]

**Pull request merged**
